// Rich demo content for hackathon business planning scenario.
// Each constant is realistic HTML that hackathon judges will read.

export const BUSINESS_CONCEPT = `<p>We're building a platform that helps small business owners plan and execute their growth strategy. The idea started when we noticed how many entrepreneurs struggle with the transition from solo founder to team leader — they know their craft inside and out, but scaling operations, hiring the right people, and choosing the right product direction all at once is overwhelming.</p>
<p>Our platform gives founders a structured way to brainstorm, compare, and commit to strategic decisions. Think of it like version control for your business plan: you can branch out into different hiring philosophies, explore multiple product directions simultaneously, and then merge the best ideas into a coherent roadmap. No more scattered Google Docs and half-forgotten whiteboard sessions.</p>
<p>The initial target market is bootstrapped SaaS founders with 1-10 employees who are past the idea stage but haven't yet found repeatable growth. We'll validate with 50 beta users from indie hacker communities before expanding to accelerator cohorts and small agency owners.</p>`

export const HIRING_STRATEGY = `<p>Before we write a single job posting, we need to decide what kind of company we want to be. Hiring is the highest-leverage decision a small team makes — every early employee shapes the culture, the velocity, and the ceiling of what's possible. Get it right and you compound; get it wrong and you spend six months cleaning up the damage.</p>
<p>We've identified three viable philosophies, each with real trade-offs. The "hire fast, fire fast" approach optimizes for speed and learning. The "culture-first" approach prioritizes long-term retention and deep alignment. The "remote-first global" approach maximizes the talent pool and enables around-the-clock coverage. None of them is universally correct — the right choice depends on our runway, our product complexity, and our founders' management experience.</p>
<p>Below, we branch into each of these three directions so we can stress-test the implications before committing. The goal is to pick one philosophy and execute it consistently, rather than hiring reactively and ending up with a Frankenstein team.</p>`

export const HIRE_FAST = `<p>The "hire fast, fire fast" philosophy is built on one core belief: you cannot predict job performance from interviews alone. Resumes lie, references are curated, and even the best behavioral questions only measure someone's ability to interview well. The only reliable signal is watching someone do the actual work.</p>
<p>Under this model, we'd run paid trial projects (1-2 weeks) with multiple candidates simultaneously. We set clear deliverables upfront, provide real context and access, and evaluate based on output quality, communication habits, and initiative. Candidates who thrive get an offer within days. Those who don't are compensated fairly and parted with respectfully. The entire cycle from posting to offer takes 3-4 weeks instead of 3-4 months.</p>
<p>The risk is real: high candidate throughput means higher onboarding costs and potential cultural whiplash if turnover spikes. But for an early-stage company racing to find product-market fit, the cost of a slow hire — months of lost momentum — almost always exceeds the cost of a fast mistake. We mitigate by keeping trial projects small, well-scoped, and genuinely useful regardless of the hiring outcome.</p>`

export const CULTURE_FIRST = `<p>Culture-first hiring means accepting that every hire will be slower, more deliberate, and more expensive upfront — because the cost of a cultural misalignment at a 5-person company is existential. When your team is small enough to fit around a dinner table, one toxic or disengaged person doesn't just hurt productivity; they fundamentally change what it feels like to come to work.</p>
<p>Our process would start with a values alignment conversation before any technical assessment. We'd share our operating principles openly — radical candor, ownership over output, async-by-default communication — and ask candidates to share examples of how they've lived (or struggled with) similar values. Only candidates who pass the values screen move to a technical deep-dive and a paid collaborative session with the existing team.</p>
<p>The onboarding period extends to 90 days with weekly 1-on-1s, a dedicated mentor, and a structured 30-60-90 plan. Yes, this means we'll fill roles more slowly. Yes, we'll lose some great candidates to faster-moving competitors. But the data from companies like Basecamp and Buffer consistently shows that culture-first teams have dramatically lower turnover, higher engagement scores, and better long-term output per employee.</p>`

export const REMOTE_GLOBAL = `<p>Going remote-first and global from day one isn't just a perk — it's a structural advantage. The best React developer for our team might be in Lagos. The best growth marketer might be in Tallinn. By removing geography as a constraint, we're fishing in an ocean instead of a pond, and we can often offer life-changing compensation in lower cost-of-living markets while staying well within our budget.</p>
<p>The operational model centers on async communication as the default. Every decision, discussion, and update lives in writing — Notion docs, Loom videos, and threaded discussions. Meetings are reserved for relationship-building, complex problem-solving, and weekly syncs that rotate across time zones. We'd target hiring across three timezone bands (Americas, Europe/Africa, Asia-Pacific) to ensure near-24-hour coverage for critical issues.</p>
<p>The challenges are well-documented: isolation, timezone friction, and the difficulty of building trust without shared physical space. We'd invest heavily in annual retreats (budget $3-5K per person), virtual social rituals, and explicit documentation of norms. Companies like GitLab and Zapier have proven this model works at scale; our job is to adapt their playbooks to a 5-10 person team where every relationship matters more.</p>`

export const PRODUCT_DIRECTION = `<p>With our team philosophy taking shape, the next critical question is: what exactly are we building? We have strong convictions about the problem space — small business owners need better tools for strategic planning — but the specific product form factor is still open. The market is large enough to support several approaches, and we need to pick the one that plays to our team's strengths and has the clearest path to revenue.</p>
<p>We've brainstormed three distinct product concepts, each targeting a different niche within the small business ecosystem. The "Pool Owners Management Tool" addresses a surprisingly underserved vertical. The "AI-Powered HR Platform" leverages the hiring expertise we've been developing. And the "Smart Home Integration Suite" targets the growing market of connected home service businesses. Each has different technical requirements, go-to-market strategies, and competitive landscapes.</p>
<p>The framework for evaluating these options is straightforward: market size and growth rate, our team's existing expertise, time to MVP, and clarity of the initial customer acquisition channel. We'll branch into each concept below, flesh out the details, and then reconvene to make a final call.</p>`

export const POOL_TOOL = `<p>The pool service industry is a $5B market in the US alone, and it's shockingly analog. Most pool service companies run on paper route sheets, text message scheduling, and QuickBooks invoices that are three weeks behind. We'd build a vertical SaaS platform that handles scheduling, chemical tracking, equipment maintenance logs, and customer communication in one place.</p>
<p>The killer feature is automated chemical dosing recommendations based on water test inputs, weather data, and pool volume. Pool technicians currently rely on experience and guesswork, leading to over-chemicaling (expensive) or under-chemicaling (algae blooms and angry customers). Our algorithm would save the average pool company $200-400 per month in chemical costs alone, making the $99/month subscription an easy sell.</p>
<p>Go-to-market is beautifully simple: pool service companies cluster geographically, attend the same trade shows (PSP Expo, Western Pool & Spa Show), and talk to each other constantly. Land one company in a market, deliver results, and referrals follow. We'd target the Sun Belt states first — Florida, Texas, Arizona, California — where pools are year-round businesses with the highest willingness to pay for efficiency tools.</p>`

export const HR_PLATFORM = `<p>What if we took everything we've learned about hiring philosophy and turned it into a product? An AI-powered HR platform specifically designed for companies with 5-50 employees — too big for informal hiring, too small for enterprise HR suites like Workday or BambooHR. The core insight is that small companies don't need "HR software." They need a hiring co-pilot that makes the entire process less painful and more predictable.</p>
<p>The platform would automate the tedious parts — job description generation, resume screening, interview scheduling — while preserving the human judgment that matters most at small scale. Our AI scoring engine would evaluate candidates on three dimensions: skill match (based on work samples, not keywords), culture alignment (based on structured interview responses), and growth trajectory (based on career progression patterns). Each dimension is transparent and adjustable, not a black-box score.</p>
<p>The monetization model is transactional: free to post and screen, $299 per successful hire. This aligns our incentives with the customer's — we only make money when they find someone great. For companies hiring 3-5 people per year, that's roughly $1,000-1,500 in annual spend, which is a fraction of what they'd pay a recruiter (typically 15-25% of first-year salary). Early traction would come from the same indie hacker and bootstrapped founder communities we're already embedded in.</p>`

export const SMART_HOME = `<p>The smart home market is exploding, but the experience is fragmented. A typical connected home runs 4-6 different apps — one for lights, one for thermostats, one for security cameras, one for door locks, one for irrigation. Each has its own account, its own notification system, and its own automation logic. We'd build the unified control hub that ties everything together with a single dashboard, unified automations, and one notification stream.</p>
<p>Our differentiator is targeting small home service businesses — property managers, Airbnb hosts, and home renovation contractors — rather than individual consumers. These users manage 5-50 properties and need fleet-level control: set all vacant properties to eco mode, get a single alert feed across all locations, and generate maintenance reports automatically. No existing solution handles this multi-property use case well.</p>
<p>The technical approach leverages Matter and Thread protocols for device communication, with a lightweight hub device (Raspberry Pi-based initially) at each property and a cloud dashboard for fleet management. Revenue comes from a per-property monthly subscription ($15/property/month) with volume discounts. A property manager with 20 units would pay $250/month — less than one hour of their time saved per week in reduced manual checking and coordination.</p>`

export const MERGED_HIRING_PRODUCT = `<p>After exploring both our hiring philosophy and product direction independently, a powerful synthesis has emerged. Our culture-first hiring approach and the AI-powered HR platform concept aren't just compatible — they're symbiotic. By building the HR platform, we dogfood our own hiring methodology, and every lesson we learn scaling our team becomes a product insight that makes the platform better.</p>
<p>The merged strategy looks like this: we hire our initial team of 5 using the culture-first methodology, meticulously documenting every step of the process. Each pain point we encounter becomes a feature spec. Each workaround we build becomes a prototype. By the time we have a team of 5, we also have a battle-tested MVP that we built for ourselves first — the most authentic form of product-market fit validation.</p>
<p>The go-to-market writes itself: "We built this because we needed it. Here's exactly how it helped us hire 5 exceptional people in 4 months, with zero regretted offers." That story resonates with every founder who's ever made a bad hire. We launch in the communities we already belong to, price it accessibly ($299/hire), and let the product compound alongside the team that builds it. Hiring strategy and product strategy become one and the same.</p>`
